// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEBgnInnrVCheVcgXCVYIBM_7Ut0HgLE',
    appId: '1:254381633034:web:9ee00eda0382c8a79739f3',
    messagingSenderId: '254381633034',
    projectId: 'ecommerce-kumar',
    authDomain: 'ecommerce-kumar.firebaseapp.com',
    storageBucket: 'ecommerce-kumar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLkRqTd4iXgGjnS5L8WFhadxFsJ1KTic',
    appId: '1:254381633034:android:86764516a3b555fb9739f3',
    messagingSenderId: '254381633034',
    projectId: 'ecommerce-kumar',
    storageBucket: 'ecommerce-kumar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU7XDt3KOlXI7JQSavhltXrhw0tjzyKUg',
    appId: '1:254381633034:ios:7f2c940e6d07339f9739f3',
    messagingSenderId: '254381633034',
    projectId: 'ecommerce-kumar',
    storageBucket: 'ecommerce-kumar.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU7XDt3KOlXI7JQSavhltXrhw0tjzyKUg',
    appId: '1:254381633034:ios:7f2c940e6d07339f9739f3',
    messagingSenderId: '254381633034',
    projectId: 'ecommerce-kumar',
    storageBucket: 'ecommerce-kumar.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEBgnInnrVCheVcgXCVYIBM_7Ut0HgLE',
    appId: '1:254381633034:web:6d85efd069e6df819739f3',
    messagingSenderId: '254381633034',
    projectId: 'ecommerce-kumar',
    authDomain: 'ecommerce-kumar.firebaseapp.com',
    storageBucket: 'ecommerce-kumar.appspot.com',
  );
}
